### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by hungerburg** [amandasaurus/osm-tag-csv-history#2]
Can this be used to get the medium count a certain key was used by distinct users? Like this: tag "fence=avalanche" got applied 1500 times; 50 users did apply this tag (therefore average is 30); the medium number was 10|50|200|whatever; That way, one could infer something about the distribution, eg. if it is flat (many users use this at about the same frequency) or shifted (some users do most of the application).

**Comment by amandasaurus** [comment]
Yes I think you could use it that way. I'm sure there could be interesting statistical research on OSM that you could do like this.

Have you heard of the Gini index ( https://en.wikipedia.org/wiki/Gini_coefficient#Definition ), it's often used to compare income (in)equality. But it could measure how spread out tag usage is. It could be more advanced than just looking at the medium.

If you do anything like this, please feel free to let me (& the rest of the OSM community) know. 🙂🙂
