### ISSUE TITLE
"You can also use this tool on regular, non-history, OSM data files."

### ISSUE THREAD

**Issue by matkoniecz** [amandasaurus/osm-tag-csv-history#3]
what is the output then? without access to history data I wonder how this tool can guess who added what

is it falling back to OSM API or listing last mapper as adding all tags on each object or what?

I want to get listings of added tags/deleted objects on relatively small changeset pools - for example I want to count how many objects were deleted (of each type) or marked as still existing in CheckExistence StreetComplete quest, what is the distribution of tags added by AddPlaygroundAccess and so on)

**Comment by amandasaurus** [comment]
On Wed, 22 Feb 2023 14:14 +01:00, Mateusz Konieczny ***@***.***> wrote:
> what is the output then? without access to history data I wonder how 
> this tool can guess who added what

https://github.com/amandasaurus/osm-tag-csv-history#non-history-files

> This programme can run on non-history files just fine. The old_value, and old_version will be empty. This can be a way to convert OSM data into CSV format for further processing.

> is it falling back to OSM API or listing last mapper as adding all tags 
> on each object or what?

No, it doesn't make any API requests

> I want to get listings of added tags/deleted objects on relatively 
> small changeset pools - for example I want to count how many objects 
> were deleted (of each type) or marked as still existing in 
> CheckExistence StreetComplete quest, what is the distribution of tags 
> added by AddPlaygroundAccess and so on)

I have a fork somewhere where it parses changeset tags (which are in the changeset dump file)

-- 
Amanda
